export const SUPPORTED_LANGUAGES = {
  PL: 'Polish (Polski)',
  EN: 'English',
  DE: 'German (Deutsch)',
  ES: 'Spanish (Español)',
  PT: 'Portuguese (Português)',
  BR: 'Portuguese (Brazilians)',
  TR: 'Turkish (Türk)',
  NL: 'Dutch (Nederlands)',
  CS: 'Czech (Čeština)',
  SK: 'Slovak (Slovenčina)',
  HU: 'Hungarian (Magyar)',
  FR: 'French (Français)',
  RO: 'Romanian (Română)',
  CN: 'Chinese (中文(简体))',
  IT: 'Italian (Italiano)',
  SV: 'Swedish (Svenska)',
  RU: 'Russian (Pусский)',
}
