export type IconsNames =
  | 'keydrop-logo'
  | 'keydrop-signet'
  | 'user-fill'
  | 'notification-fill'
  | 'settings-fill'
  | 'wallet-fill'
  | 'cases-fill'
  | 'upgrades-fill'
  | 'contracts-fill'
  | 'battles-fill'
  | 'daily-fill'
  | 'hand-with-coins-fill'
  | 'success-fill'
  | 'exchange-fill'
  | 'pending-fill'
  | 'question-fill'
  | 'new-fill'
