name: "[DEVELOP] Build Extension"

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

env:
  VERSION: "v_x_x_x"

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version from package.json
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .
      - run: echo "VERSION=${ steps.get-version.outputs.version/.//_ }" >> $GITHUB_ENV

  chromium-dev:
    runs-on: ubuntu-latest
    needs:
      - version
    if: needs.version.result == 'success'
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - run: yarn install --frozen-lockfile
      - run: yarn build:chromium
        env:
          REACT_APP_SESSION_COOKIE_NAME: ${{ secrets.REACT_APP_SESSION_COOKIE_NAME }}
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
      - name: Archive production artifacts
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: kd_ext_staging_chromium_${{ env.VERSION }}
          path: build

  chromium-prod:
    runs-on: ubuntu-latest
    needs:
      - version
    if: needs.version.result == 'success'
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - run: yarn install --frozen-lockfile
      - run: yarn build:chromium:prod
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kd_ext_prod_chromium_${{ env.VERSION }}
          path: build

  gecko-dev:
    runs-on: ubuntu-latest
    needs:
      - version
    if: needs.version.result == 'success'
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - run: yarn install --frozen-lockfile
      - run: yarn build:gecko
        env:
          REACT_APP_SESSION_COOKIE_NAME: ${{ secrets.REACT_APP_SESSION_COOKIE_NAME }}
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kd_ext_staging_gecko_${{ env.VERSION }}
          path: build

  gecko-prod:
    runs-on: ubuntu-latest
    needs:
      - version
    if: needs.version.result == 'success'
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - run: yarn install --frozen-lockfile
      - run: yarn build:gecko:prod
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kd_ext_prod_gecko_${{ env.VERSION }}
          path: build

  source-code:
    runs-on: ubuntu-latest
    needs:
      - version
    if: needs.version.result == 'success'
    steps:
      - uses: actions/checkout@v3
      - name: Create zip
        run: git archive -o kd_ext_source_${{ env.VERSION }}.zip develop
      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: kd_ext_source_${{ env.VERSION }}
          path: kd_ext_source_${{ env.VERSION }}.zip
