name: "[MAIN] Build Extension"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  chromium-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - name: Get version from package.json
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
         path: .
      - run: yarn install --frozen-lockfile
      - run: yarn build:chromium:prod
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kd_ext_v${{ steps.get-version.outputs.version }}_prod_chromium
          path: build

  gecko-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - name: Get version from package.json
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .
      - run: yarn install --frozen-lockfile
      - run: yarn build:gecko:prod
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kd_ext_v${{ steps.get-version.outputs.version }}_prod_gecko
          path: build
