name: "[DEVELOP] Build Extension"

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  chromium-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - name: Get version from package.json
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .
      - run: yarn install --frozen-lockfile
      - run: yarn build:chromium
        env:
          REACT_APP_SESSION_COOKIE_NAME: ${{ secrets.REACT_APP_SESSION_COOKIE_NAME }}
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kd_ext_v${{ steps.get-version.outputs.version/\//- }}_staging_chromium
          path: build

  chromium-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - name: Get version from package.json
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .
      - run: yarn install --frozen-lockfile
      - run: yarn build:chromium:prod
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kd_ext_v${{ steps.get-version.outputs.version/\//- }}_prod_chromium
          path: build

  gecko-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - name: Get version from package.json
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .
      - run: yarn install --frozen-lockfile
      - run: yarn build:gecko
        env:
          REACT_APP_SESSION_COOKIE_NAME: ${{ secrets.REACT_APP_SESSION_COOKIE_NAME }}
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kd_ext_v${{ steps.get-version.outputs.version/\//- }}_staging_gecko
          path: build

  gecko-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - name: Get version from package.json
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .
      - run: yarn install --frozen-lockfile
      - run: yarn build:gecko:prod
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kd_ext_v${{ steps.get-version.outputs.version/\//- }}_prod_gecko
          path: build

  source-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get version from package.json
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .
      - name: Create zip
        run: git archive -o kd_ext_v${{ steps.get-version.outputs.version/\//- }}_source.zip develop
      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: kd_ext_v${{ steps.get-version.outputs.version/\//- }}_source
          path: kd_ext_v${{ steps.get-version.outputs.version/\//- }}_source.zip
