name: "[DEV] Build Extension"

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  chromium-dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: "yarn"
        cache-dependency-path: yarn.lock
    - run: yarn install --frozen-lockfile
    - run: yarn build:chromium
      env:
        REACT_APP_SESSION_COOKIE_NAME: ${{ secrets.REACT_APP_SESSION_COOKIE_NAME }}
        REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: chromium-dev-build
        path: build
  gecko-dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - run: yarn install --frozen-lockfile
      - run: yarn build:gecko
        env:
          REACT_APP_SESSION_COOKIE_NAME: ${{ secrets.REACT_APP_SESSION_COOKIE_NAME }}
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gecko-dev-build
          path: build
  chromium-prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - run: yarn install --frozen-lockfile
      - run: yarn build:chromium:prod
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: chromium-prod-build
          path: build
  gecko-prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - run: yarn install --frozen-lockfile
      - run: yarn build:gecko:prod
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gecko-prod-build
          path: build
